x=msgbox("Please Confirm that you want to Access This PC....",3+64,"Computer Access....") 
x=msgbox("Click Ok To Continue with Computer Access.",1+48,"Continue...") 
x=msgbox("Please Wait While Accessing Files.....",1+64,"Trying To Access Files...") 
x=msgbox("Do you Have an Authorized Access to This PC ?",3+16,"Authorization....") 
x=msgbox("Sorry..You Do not have an Authorized Access to This Pc..Please Request for Authorization From the Owner or try Again... ",2+64,"Alert!!Warning!!") 
x=msgbox("Please Wait as Retrying continues....",1+16,"Retrying......") 
x=msgbox("Failed...You dont have an Authorized Access to This PC....",2+48,"Failed.") 
x=msgbox("Error....Please Request For Assistance from Billy.",1+48,"Try Fixing This Problem.") 
x=msgbox("Kindly Wait as Billy Is Trying To assist You....",1+64,"Recieving Help From Billy......") 
x=msgbox("Billy Has Denied You Access And Requires to see you Personally.Do you Wish to see Him In Person?",4+16,"Access Denied!!") 
x=msgbox("Thank You For Your Patience...Billy is Waiting for You...",1+64,"Billy Obuya Waiting...") 
x=msgbox("By the way ..sorry for the great disturbance made to you by Billy Obuya..This was just a prank and a dummy shortcurt of This PC..please look For the Actual Shortcurt.. ",1+48,"Apology From Billy obuya....") 
x=msgbox("Bye Bye.",0+16,"Billy Was Here.") 

