x=msgbox("Error while opening This Pc",1+64,"My Pc")
x=msgbox("Error could not be removed.Do you want to Scan This Pc?",3+48,"Scan This Pc")
x=msgbox("Virus detected in This Pc.Do you want the Virus to be removed?",4+16,"Remove Virus")
x=msgbox("Please Wait As the virus is being removed.......",1+64,"Removing Virus......")
x=msgbox("The Virus could not be Removed.Please Try Again.",2+48,"Try Again.")
x=msgbox("Someone is trying to Access This Pc.......",2+16,"Alert!!!Warning!!!")
x=msgbox("Copying Files from This Pc to the Hacker Server....",2+64,"Copying All Files....")
x=msgbox("Copying your Password to the Hack server.....",2+16,"Copying User Password......")
x=msgbox("Sorry....This Pc has been Hacked by unknown source....!!!!",2+48,"Hacking Successful......")
x=msgbox("Failed!!!!You Dont have any access to This Pc Completely....!!!",2+16,"Warning!!!Access denied!!!!")
x=msgbox("Warning!!!This Pc can only be Accessed by the Hack Server.",1+64,"Alert Message!!")
x=msgbox("Just be relaxed.Your Pc and all your Files Are safe and Sound.This was just a hack prank by Billy The Hacker.Be Warned!!!",1+48,"Current Status of This Pc and Files..... ")
x=msgbox("I think you should find The individual Billy and deal With Him.",4+64,"Find Hack Server.")
x=msgbox("Anyway Goodbye...Feel at The Feet Of Programming and Hacking.....You can continue to have access To Your Pc but remember Billy was Here",1+64,"Message From Billy Obuya....!!")

